version: 2
updates:
  - package-ecosystem: "npm" # Cambia por el ecosistema correspondiente (ej. pip, maven, etc.)
    directory: "/" # Carpeta donde se encuentra el archivo de dependencias
    schedule:
      interval: "daily" # Frecuencia de las actualizaciones